"""drop unique constraint on user_id

Revision ID: 810c229300c8
Revises: 7c8219c58af0
Create Date: 2026-03-24 16:26:02.297574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810c229300c8'
down_revision: Union[str, Sequence[str], None] = '7c8219c58af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_messages_user_id'), table_name='user_messages')
    op.create_index(op.f('ix_user_messages_user_id'), 'user_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_messages_user_id'), table_name='user_messages')
    op.create_index(op.f('ix_user_messages_user_id'), 'user_messages', ['user_id'], unique=True)
    # ### end Alembic commands ###
